name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Convert gradlew to Unix format
      run: |
        sudo apt-get install -y dos2unix
        dos2unix gradlew

    - name: Verify gradlew line endings
      run: |
        file gradlew
        head -n 5 gradlew

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Decode Keystore
      if: env.ANDROID_KEYSTORE_BASE64 != ''
      run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

    - name: Build Signed Release APK
      if: env.ANDROID_KEYSTORE_BASE64 != ''
      run: ./gradlew assembleRelease \
        -Pandroid.injected.signing.store.file=keystore.jks \
        -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
        -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} \
        -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Upload Signed Release APK
      if: env.ANDROID_KEYSTORE_BASE64 != ''
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed
        path: app/build/outputs/apk/release/app-release.apk
